backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Categoría", name: "category", widget: "string"}
      - label: "Etiquetas"
        name: "tags"
        widget: "list"
      - label: "Imagen destacada"
        name: "image"
        widget: "object"
        fields:
          - {label: "Imagen", name: "url", widget: "image"}
          - {label: "Alt", name: "alt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
